### ISSUE TITLE
global is not defined while used with browserify

### ISSUE THREAD

**Issue by Hiswe** [bevacqua/dominus#2]
Hi,

Thank you for this lib! 

I'm using dominus packed with browserify.
When trying to do something like this:

```js
$('.selector').on('click', function(e) {
  e.preventDefault();
  var $item = $(e.currentTarget); // throw an error
});
```

I've got an `Uncaught ReferenceError: global is not defined` 
This come from [cast.js](https://github.com/bevacqua/dominus/blob/master/src/cast.js#L8).

I have tested it without browserify using the dist files, and the problem doesn't seems to show.

Do you have an idea about how I can fix this issue?

Thanks in advance :)

**Comment by Hiswe** [comment]
As a workaround I've done this:

```js
window.global     = window;
```

which is not perfect but… it works :)

**Comment by bevacqua** [comment]
Sure. If you use browserify then `dominus` isn't global, just use `require('dominus')`. Otherwise use the file in `dist`.

**Comment by Hiswe** [comment]
@bevacqua sorry, I wasn't clear enough. But thanks for the answer!

I've made a demo (still using browserify) to show you the problem:

www.googledrive.com/host/0B5WqGSF-8XAVOGI5dW13SUdDMW8

You can open the console and click on the black square.

___

A copy of the JS code:

```js
'use strict';
var $   = require('dominus');
var $p  = $('p');
$('div').on('click', function (e) {
  try { 
    $(e.currentTarget);
  } catch (e) {
    $p
      .css('opacity', 1)
      .html(e);
  }
  $(e.currentTarget);
});
```
and that's the error stack in the console:

```
Uncaught ReferenceError: global is not defined

cast                  @ cast.js:8
api                   @ public.js:12
(anonymous function)  @ index.js:14
```
